// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMQCwVDVCDn4Z88lJlx55tQd2fnYDrxwE',
    appId: '1:153811452823:web:d5aafe3d202c8cf8ecbad2',
    messagingSenderId: '153811452823',
    projectId: 'dss-project-e2da9',
    authDomain: 'dss-project-e2da9.firebaseapp.com',
    storageBucket: 'dss-project-e2da9.firebasestorage.app',
    measurementId: 'G-03PT4V8D6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoEXxZLhBWYgi0lDdVtLedwegZkzFCPOE',
    appId: '1:153811452823:android:5151918e5cb17738ecbad2',
    messagingSenderId: '153811452823',
    projectId: 'dss-project-e2da9',
    storageBucket: 'dss-project-e2da9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOImr6ynVTsd8vJyERc5x4W4KLDl23aEk',
    appId: '1:153811452823:ios:88d3873e2d65b974ecbad2',
    messagingSenderId: '153811452823',
    projectId: 'dss-project-e2da9',
    storageBucket: 'dss-project-e2da9.firebasestorage.app',
    iosBundleId: 'com.example.dssProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOImr6ynVTsd8vJyERc5x4W4KLDl23aEk',
    appId: '1:153811452823:ios:88d3873e2d65b974ecbad2',
    messagingSenderId: '153811452823',
    projectId: 'dss-project-e2da9',
    storageBucket: 'dss-project-e2da9.firebasestorage.app',
    iosBundleId: 'com.example.dssProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMQCwVDVCDn4Z88lJlx55tQd2fnYDrxwE',
    appId: '1:153811452823:web:6a09b279fd7b47b0ecbad2',
    messagingSenderId: '153811452823',
    projectId: 'dss-project-e2da9',
    authDomain: 'dss-project-e2da9.firebaseapp.com',
    storageBucket: 'dss-project-e2da9.firebasestorage.app',
    measurementId: 'G-MP770496C4',
  );
}
